import type { WalkerNetworkConfig } from "../simulation/types";

export const walkerNetworkConfig: WalkerNetworkConfig = {
  constellation: {
    walkerType: "star",
    shellId: "starlink-main-shell-lite-8x8",
    planes: 8,
    satellitesPerPlane: 8,
    phasing: 1,
    altitudeKm: 550,
    inclinationDeg: 53,
    earthRadiusKm: 6371,
    gravitationalParameterKm3S2: 398600.4418,
  },
  time: {
    epochIso: "2026-06-16T00:00:00.000Z",
    slices: 48,
    stepMinutes: 5,
  },
  orbit: {
    model: "analytic-walker",
    tleCatalog: {
      source: "synthetic-starlink-main-shell",
      noradBaseId: 99000,
      satelliteNamePrefix: "STARLINK-LIKE",
      cosparYear: 2026,
      cosparLaunchNumber: 1,
      eccentricity: 0.0002,
      bstar: 0.00001,
    },
  },
  interPlane: {
    maxDistanceKm: 3600,
    warningMarginKm: 450,
    maxLinksPerNode: 4,
  },
  polarRegion: {
    enabled: true,
    latitudeDeg: 50,
  },
  earthOcclusion: {
    enabled: true,
    clearanceKm: 25,
  },
  nodeStateDefaults: {
    mode: "nominal",
    batteryPercent: 88,
    cpuLoadPercent: 34,
    temperatureC: 18,
    queueDepth: 16,
  },
  nodeResourceDefaults: {
    node_type: "satellite",
    cpu_capacity: 256,
    gpu_capacity: 32,
    memory: 128,
    storage: 4096,
    energy: 72,
    energy_wh: 864,
    battery_capacity_wh: 1200,
    state_of_charge: 0.72,
    min_state_of_charge: 0.2,
    solar_power_w: 0,
    load_power_w: 330,
    net_power_w: -347.37,
    power_saving_mode: false,
    cpu_utilization: 0,
    compute_cpu_percent: 0,
    task_traffic_cpu_percent: 0,
    forwarding_cpu_percent: 0,
    queue_cpu_percent: 0,
    gpu_utilization: 0,
    memory_utilization: 0,
    storage_utilization: 0,
    can_accept_tasks: true,
    assigned_task_count: 0,
    workload_cpu_percent: 0,
    workload_gpu_percent: 0,
    workload_memory_gb: 0,
    workload_storage_gb: 0,
    memory_used_gb: 0,
    storage_used_gb: 0,
    ingress_traffic_mbps: 0,
    egress_traffic_mbps: 0,
    transit_traffic_mbps: 0,
    queued_traffic_mb: 0,
    dropped_traffic_mb: 0,
    cache_used_mb: 0,
    cache_utilization: 0,
    telemetry_generated_mb: 0,
    telemetry_buffer_mb: 0,
    telemetry_downlinked_mb: 0,
    telemetry_dropped_mb: 0,
    forwarding_load_mbps: 0,
    downlink_load_mbps: 0,
    active_isl_links: 0,
    active_sgl_links: 0,
    link_occupancy_percent: 0,
    base_power_w: 80,
    payload_power_w: 100,
    task_compute_power_w: 0,
    network_compute_power_w: 0,
    communication_power_w: 0,
  },
  operationalModel: {
    solarConstantWPerM2: 1361,
    solarArrayAreaM2: 2,
    solarArrayEfficiency: 0.28,
    batteryCapacityWh: 1200,
    basePowerW: 80,
    communicationPowerW: 100,
    computePowerW: 50,
    payloadPowerW: 100,
    chargeEfficiency: 0.95,
    dischargeEfficiency: 0.95,
    minStateOfCharge: 0.2,
    cpuLoadPerComputeUnit: 0.39,
    gpuLoadPerGpuUnit: 3.13,
    memoryPercentPerGb: 0.78,
    storagePercentPerGb: 0.024,
    queueDepthPerTask: 4,
    thermalRisePerCpuPercent: 0.08,
    thermalRisePerGpuPercent: 0.035,
    thermalRisePerCommunicationW: 0.012,
    queueMemoryGbPerQueuedGb: 0.08,
    telemetryMemoryGbPerBufferedGb: 0.03,
    cacheStorageGbPerBufferedGb: 1,
  },
  routing: {
    algorithm: "congestion-aware-shortest-path",
  },
  trafficModel: {
    normalFlowCount: 24,
    normalFlowMinMbps: 130,
    normalFlowMaxMbps: 560,
    normalFlowDurationSlices: 8,
    normalFlowComputeUnits: 24,
    endpointCpuPercentPerGbps: 15,
    endpointQueueDepthPerGbps: 12.5,
    forwardingCpuPercentPerGbps: 6,
    forwardingPowerWPerGbps: 28,
    activeIslLinkPowerW: 3,
    activeSglLinkPowerW: 5,
    queueCpuPercentPerGb: 0.35,
    queuePowerWPerGb: 1.2,
    queueDepthPerQueuedMb: 0.18,
    queueCarryoverRatio: 0.65,
    linkQueueCapacityMb: 16384,
    maxRouteQueueDelayMs: 30000,
    taskTimeoutMs: 30000,
    cacheCapacityMb: 8192,
    telemetryGenerationMbPerSlice: 18,
    telemetryCpuMbPerPercent: 0.03,
    telemetryTrafficMbPerGbps: 1.8,
    telemetryCongestionMbPerPercent: 0.12,
    telemetryTaskSamplingRatio: 0.02,
    downlinkTaskSamplingRatio: 0.03,
    telemetryBufferCapacityMb: 2048,
  },
  antennaModel: {
    isl: {
      band: "laser",
      gainDbi: 105,
      beamwidthDeg: 1.2,
      maxRangeKm: 6500,
      maxTxPowerW: 40,
      bandwidthMbps: 2500,
      maxSimultaneousBeams: 1,
      slewRateDegPerSec: 1.5,
    },
    sgl: {
      band: "Ka",
      gainDbi: 34,
      beamwidthDeg: 8,
      maxRangeKm: 4200,
      maxTxPowerW: 30,
      bandwidthMbps: 1200,
      maxSimultaneousBeams: 1,
      slewRateDegPerSec: 4,
      minElevationDeg: 25,
      reportCapacityMbps: 600,
    },
  },
  linkBudget: {
    isl: {
      frequencyGhz: 193500,
      channelBandwidthMhz: 2500,
      noiseFigureDb: 3,
      implementationLossDb: 2,
      atmosphericLossDb: 0,
      polarizationLossDb: 0.5,
      pointingLossDb: 2,
      capacityEfficiency: 0.65,
      minSnrDb: 6,
      warningMarginDb: 4,
      minCapacityMbps: 100,
    },
    sgl: {
      frequencyGhz: 20,
      channelBandwidthMhz: 600,
      noiseFigureDb: 2.5,
      implementationLossDb: 2,
      atmosphericLossDb: 1.2,
      polarizationLossDb: 0.5,
      pointingLossDb: 1.5,
      capacityEfficiency: 0.58,
      minSnrDb: 5,
      warningMarginDb: 4,
      minCapacityMbps: 50,
      groundStationGainDbi: 48,
    },
  },
  interferenceModel: {
    isl: {
      enabled: true,
      reuseChannelCount: 4,
      channelSpacingMhz: 2500,
      coChannelIsolationDb: 3,
      adjacentChannelIsolationDb: 24,
      adjacentChannelRollOffDbPerStep: 12,
      maxAdjacentChannelSeparation: 2,
      polarizationIsolationDb: 3,
      sideLobeSuppressionDb: 35,
      frontBackSuppressionDb: 65,
      selfInterferenceIsolationDb: 110,
      offAxisRollOffDbPerDecade: 20,
      minSideLobeGainDbi: 18,
      minInterferencePowerDbm: -140,
    },
    sgl: {
      enabled: true,
      reuseChannelCount: 3,
      channelSpacingMhz: 600,
      coChannelIsolationDb: 8,
      adjacentChannelIsolationDb: 28,
      adjacentChannelRollOffDbPerStep: 14,
      maxAdjacentChannelSeparation: 1,
      polarizationIsolationDb: 3,
      sideLobeSuppressionDb: 32,
      frontBackSuppressionDb: 55,
      selfInterferenceIsolationDb: 100,
      offAxisRollOffDbPerDecade: 25,
      minSideLobeGainDbi: -5,
      minInterferencePowerDbm: -135,
      groundAntennaBeamwidthDeg: 2.4,
    },
  },
  pointingModel: {
    enabled: true,
    acquisitionTimeSeconds: 2,
    trackingLoopLagSeconds: 0.8,
    minAvailableFraction: 0.85,
    warningAvailableFraction: 0.96,
    isl: {
      pointingJitterDeg: 0.05,
    },
    sgl: {
      pointingJitterDeg: 0.15,
    },
  },
  dopplerModel: {
    enabled: true,
    isl: {
      compensationRangeHz: 12_000_000_000,
      residualFraction: 0.0005,
      residualFloorHz: 1000,
      maxResidualHz: 25_000_000,
      warningResidualHz: 15_000_000,
      maxDopplerLossDb: 2,
    },
    sgl: {
      compensationRangeHz: 900_000,
      residualFraction: 0.02,
      residualFloorHz: 200,
      maxResidualHz: 60_000,
      warningResidualHz: 35_000,
      maxDopplerLossDb: 1.5,
    },
  },
  noiseModel: {
    enabled: true,
    isl: {
      receiverReferenceTemperatureK: 290,
      quietSkyTemperatureK: 5,
      sunNoiseTemperatureK: 1500,
      sunAngularRadiusDeg: 0.27,
      mainLobeCoupling: 0.12,
      sideLobeCoupling: 0.002,
      warningNoiseIncreaseDb: 1,
      solarExclusionAngleDeg: 6,
      solarWarningAngleDeg: 12,
      maxSolarInterferenceLossDb: 6,
    },
    sgl: {
      receiverReferenceTemperatureK: 290,
      quietSkyTemperatureK: 25,
      sunNoiseTemperatureK: 120000,
      sunAngularRadiusDeg: 0.27,
      mainLobeCoupling: 1,
      sideLobeCoupling: 0.01,
      warningNoiseIncreaseDb: 1.5,
      solarExclusionAngleDeg: 0,
      solarWarningAngleDeg: 0,
      maxSolarInterferenceLossDb: 0,
    },
  },
  atmosphericModel: {
    sgl: {
      enabled: true,
      rainSpecificAttenuationK: 0.075,
      rainSpecificAttenuationAlpha: 1.1,
      rainPathReductionReferenceKm: 35,
      cloudSpecificAttenuationDbPerKgM2: 0.12,
      minElevationForLossDeg: 5,
    },
  },
  adaptiveCoding: {
    isl: {
      enabled: true,
      packetSizeBytes: 1024,
      targetPacketErrorRate: 0.001,
      schemes: [
        { id: "ISL-BPSK-1/2", modulation: "BPSK", codeRate: 0.5, spectralEfficiencyBpsHz: 0.5, requiredSinrDb: 1.5, codingGainDb: 4 },
        { id: "ISL-QPSK-1/2", modulation: "QPSK", codeRate: 0.5, spectralEfficiencyBpsHz: 1, requiredSinrDb: 3.5, codingGainDb: 4.5 },
        { id: "ISL-QPSK-3/4", modulation: "QPSK", codeRate: 0.75, spectralEfficiencyBpsHz: 1.5, requiredSinrDb: 6, codingGainDb: 4.8 },
        { id: "ISL-8PSK-2/3", modulation: "8PSK", codeRate: 0.67, spectralEfficiencyBpsHz: 2, requiredSinrDb: 8.5, codingGainDb: 5 },
        { id: "ISL-16QAM-3/4", modulation: "16QAM", codeRate: 0.75, spectralEfficiencyBpsHz: 3, requiredSinrDb: 13.5, codingGainDb: 5.5 },
        { id: "ISL-64QAM-3/4", modulation: "64QAM", codeRate: 0.75, spectralEfficiencyBpsHz: 4.5, requiredSinrDb: 19.5, codingGainDb: 6 },
      ],
    },
    sgl: {
      enabled: true,
      packetSizeBytes: 1024,
      targetPacketErrorRate: 0.001,
      schemes: [
        { id: "SGL-BPSK-1/2", modulation: "BPSK", codeRate: 0.5, spectralEfficiencyBpsHz: 0.5, requiredSinrDb: 1.5, codingGainDb: 4 },
        { id: "SGL-QPSK-1/2", modulation: "QPSK", codeRate: 0.5, spectralEfficiencyBpsHz: 1, requiredSinrDb: 3, codingGainDb: 4.2 },
        { id: "SGL-QPSK-3/4", modulation: "QPSK", codeRate: 0.75, spectralEfficiencyBpsHz: 1.5, requiredSinrDb: 5.5, codingGainDb: 4.6 },
        { id: "SGL-8PSK-2/3", modulation: "8PSK", codeRate: 0.67, spectralEfficiencyBpsHz: 2, requiredSinrDb: 8, codingGainDb: 4.8 },
        { id: "SGL-16QAM-3/4", modulation: "16QAM", codeRate: 0.75, spectralEfficiencyBpsHz: 3, requiredSinrDb: 12.5, codingGainDb: 5.2 },
      ],
    },
  },
  groundStations: [
    {
      ground_station_id: "GS-BEIJING",
      name: "北京密云站",
      latitudeDeg: 40.45,
      longitudeDeg: 116.86,
      altitudeKm: 0.12,
      minElevationDeg: 25,
      weather: {
        rainRateMmPerHour: 1.2,
        rainHeightKm: 4.5,
        gaseousZenithLossDb: 0.16,
        cloudLiquidWaterKgPerM2: 0.08,
        scintillationFadeDb: 0.18,
      },
      weatherTimeline: [
        { minute: 0, rainRateMmPerHour: 0.6, rainHeightKm: 4.1, gaseousZenithLossDb: 0.14, cloudLiquidWaterKgPerM2: 0.05, scintillationFadeDb: 0.12 },
        { minute: 30, rainRateMmPerHour: 1.8, rainHeightKm: 4.5, gaseousZenithLossDb: 0.16, cloudLiquidWaterKgPerM2: 0.1, scintillationFadeDb: 0.2 },
        { minute: 60, rainRateMmPerHour: 4.5, rainHeightKm: 4.9, gaseousZenithLossDb: 0.18, cloudLiquidWaterKgPerM2: 0.16, scintillationFadeDb: 0.32 },
        { minute: 90, rainRateMmPerHour: 1.4, rainHeightKm: 4.3, gaseousZenithLossDb: 0.15, cloudLiquidWaterKgPerM2: 0.08, scintillationFadeDb: 0.18 },
        { minute: 120, rainRateMmPerHour: 0.5, rainHeightKm: 4.0, gaseousZenithLossDb: 0.13, cloudLiquidWaterKgPerM2: 0.04, scintillationFadeDb: 0.1 },
      ],
    },
    {
      ground_station_id: "GS-KASHGAR",
      name: "新疆喀什站",
      latitudeDeg: 39.47,
      longitudeDeg: 75.99,
      altitudeKm: 1.29,
      minElevationDeg: 20,
      weather: {
        rainRateMmPerHour: 0.1,
        rainHeightKm: 3.6,
        gaseousZenithLossDb: 0.08,
        cloudLiquidWaterKgPerM2: 0.02,
        scintillationFadeDb: 0.1,
      },
      weatherTimeline: [
        { minute: 0, rainRateMmPerHour: 0.02, rainHeightKm: 3.4, gaseousZenithLossDb: 0.07, cloudLiquidWaterKgPerM2: 0.01, scintillationFadeDb: 0.06 },
        { minute: 30, rainRateMmPerHour: 0.05, rainHeightKm: 3.5, gaseousZenithLossDb: 0.08, cloudLiquidWaterKgPerM2: 0.02, scintillationFadeDb: 0.08 },
        { minute: 60, rainRateMmPerHour: 0.2, rainHeightKm: 3.7, gaseousZenithLossDb: 0.09, cloudLiquidWaterKgPerM2: 0.03, scintillationFadeDb: 0.12 },
        { minute: 90, rainRateMmPerHour: 0.08, rainHeightKm: 3.5, gaseousZenithLossDb: 0.08, cloudLiquidWaterKgPerM2: 0.02, scintillationFadeDb: 0.09 },
        { minute: 120, rainRateMmPerHour: 0.02, rainHeightKm: 3.4, gaseousZenithLossDb: 0.07, cloudLiquidWaterKgPerM2: 0.01, scintillationFadeDb: 0.06 },
      ],
    },
    {
      ground_station_id: "GS-WENCHANG",
      name: "海南文昌站",
      latitudeDeg: 19.61,
      longitudeDeg: 110.75,
      altitudeKm: 0.04,
      minElevationDeg: 25,
      weather: {
        rainRateMmPerHour: 8,
        rainHeightKm: 5.2,
        gaseousZenithLossDb: 0.22,
        cloudLiquidWaterKgPerM2: 0.3,
        scintillationFadeDb: 0.35,
      },
      weatherTimeline: [
        { minute: 0, rainRateMmPerHour: 3.5, rainHeightKm: 4.8, gaseousZenithLossDb: 0.18, cloudLiquidWaterKgPerM2: 0.18, scintillationFadeDb: 0.24 },
        { minute: 25, rainRateMmPerHour: 12, rainHeightKm: 5.2, gaseousZenithLossDb: 0.22, cloudLiquidWaterKgPerM2: 0.38, scintillationFadeDb: 0.46 },
        { minute: 55, rainRateMmPerHour: 28, rainHeightKm: 5.8, gaseousZenithLossDb: 0.28, cloudLiquidWaterKgPerM2: 0.72, scintillationFadeDb: 0.72 },
        { minute: 85, rainRateMmPerHour: 10, rainHeightKm: 5.1, gaseousZenithLossDb: 0.22, cloudLiquidWaterKgPerM2: 0.34, scintillationFadeDb: 0.42 },
        { minute: 120, rainRateMmPerHour: 4, rainHeightKm: 4.7, gaseousZenithLossDb: 0.18, cloudLiquidWaterKgPerM2: 0.2, scintillationFadeDb: 0.26 },
      ],
    },
    {
      ground_station_id: "GS-FAIRBANKS",
      name: "阿拉斯加费尔班克斯站",
      latitudeDeg: 64.84,
      longitudeDeg: -147.72,
      altitudeKm: 0.14,
      minElevationDeg: 20,
      weather: {
        rainRateMmPerHour: 0.4,
        rainHeightKm: 2.6,
        gaseousZenithLossDb: 0.12,
        cloudLiquidWaterKgPerM2: 0.06,
        scintillationFadeDb: 0.16,
      },
      weatherTimeline: [
        { minute: 0, rainRateMmPerHour: 0.15, rainHeightKm: 2.2, gaseousZenithLossDb: 0.1, cloudLiquidWaterKgPerM2: 0.04, scintillationFadeDb: 0.1 },
        { minute: 30, rainRateMmPerHour: 0.35, rainHeightKm: 2.5, gaseousZenithLossDb: 0.12, cloudLiquidWaterKgPerM2: 0.06, scintillationFadeDb: 0.15 },
        { minute: 60, rainRateMmPerHour: 1.2, rainHeightKm: 2.9, gaseousZenithLossDb: 0.15, cloudLiquidWaterKgPerM2: 0.12, scintillationFadeDb: 0.26 },
        { minute: 90, rainRateMmPerHour: 0.6, rainHeightKm: 2.6, gaseousZenithLossDb: 0.13, cloudLiquidWaterKgPerM2: 0.08, scintillationFadeDb: 0.18 },
        { minute: 120, rainRateMmPerHour: 0.2, rainHeightKm: 2.3, gaseousZenithLossDb: 0.1, cloudLiquidWaterKgPerM2: 0.04, scintillationFadeDb: 0.1 },
      ],
    },
    {
      ground_station_id: "GS-REDMOND",
      name: "Representative Redmond gateway",
      latitudeDeg: 47.67,
      longitudeDeg: -122.12,
      altitudeKm: 0.05,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 1.6, rainHeightKm: 3.4, gaseousZenithLossDb: 0.12, cloudLiquidWaterKgPerM2: 0.14, scintillationFadeDb: 0.18 },
    },
    {
      ground_station_id: "GS-LOS-ANGELES",
      name: "Representative US west gateway",
      latitudeDeg: 34.05,
      longitudeDeg: -118.25,
      altitudeKm: 0.09,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 0.3, rainHeightKm: 3.8, gaseousZenithLossDb: 0.1, cloudLiquidWaterKgPerM2: 0.04, scintillationFadeDb: 0.1 },
    },
    {
      ground_station_id: "GS-SANTIAGO",
      name: "Representative South America gateway",
      latitudeDeg: -33.45,
      longitudeDeg: -70.66,
      altitudeKm: 0.57,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 0.5, rainHeightKm: 4, gaseousZenithLossDb: 0.11, cloudLiquidWaterKgPerM2: 0.05, scintillationFadeDb: 0.12 },
    },
    {
      ground_station_id: "GS-MADRID",
      name: "Representative Europe west gateway",
      latitudeDeg: 40.43,
      longitudeDeg: -3.7,
      altitudeKm: 0.65,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 0.7, rainHeightKm: 3.9, gaseousZenithLossDb: 0.12, cloudLiquidWaterKgPerM2: 0.06, scintillationFadeDb: 0.13 },
    },
    {
      ground_station_id: "GS-FRANKFURT",
      name: "Representative Europe central gateway",
      latitudeDeg: 50.11,
      longitudeDeg: 8.68,
      altitudeKm: 0.11,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 1.1, rainHeightKm: 3.5, gaseousZenithLossDb: 0.12, cloudLiquidWaterKgPerM2: 0.1, scintillationFadeDb: 0.17 },
    },
    {
      ground_station_id: "GS-CAPE-TOWN",
      name: "Representative Africa gateway",
      latitudeDeg: -33.92,
      longitudeDeg: 18.42,
      altitudeKm: 0.03,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 0.8, rainHeightKm: 4.2, gaseousZenithLossDb: 0.13, cloudLiquidWaterKgPerM2: 0.07, scintillationFadeDb: 0.14 },
    },
    {
      ground_station_id: "GS-SINGAPORE",
      name: "Representative equatorial gateway",
      latitudeDeg: 1.35,
      longitudeDeg: 103.82,
      altitudeKm: 0.02,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 14, rainHeightKm: 5.1, gaseousZenithLossDb: 0.24, cloudLiquidWaterKgPerM2: 0.48, scintillationFadeDb: 0.48 },
    },
    {
      ground_station_id: "GS-SYDNEY",
      name: "Representative Oceania gateway",
      latitudeDeg: -33.86,
      longitudeDeg: 151.21,
      altitudeKm: 0.06,
      minElevationDeg: 15,
      weather: { rainRateMmPerHour: 1.3, rainHeightKm: 4.4, gaseousZenithLossDb: 0.14, cloudLiquidWaterKgPerM2: 0.12, scintillationFadeDb: 0.18 },
    },
  ],
  linkStateDefaults: {
    status: "up",
    bandwidthMbps: 2500,
    latencyMs: 0.25,
    utilizationPercent: 36,
    demandTrafficMbps: 0,
    carriedTrafficMbps: 0,
    queuedTrafficMb: 0,
    droppedTrafficMb: 0,
    congestionPercent: 0,
    distanceKm: 0,
  },
  stateProfiles: {
    nodeThermalWaveC: 12,
    nodeLoadWavePercent: 42,
    queueWaveDepth: 28,
    linkUtilizationWavePercent: 52,
    distanceLatencyDivisor: 300,
  },
};
